apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: connector-email
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: connector-email
    app.kubernetes.io/part-of: notifications-backend
  name: connector-email
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: connector-email
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: connector-email
    spec:
      containers:
      - image: java-quarkus-image:latest
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9003
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
