apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-microsoft-teams
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-microsoft-teams@sha256:d72134ba63794b93f5e9c0c9409e690d7a1bc143b3119d486307e765a3dca656
        name: my-java-quarkus
        resources: {}
status: {}
