apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-microsoft-teams
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-microsoft-teams@sha256:226308e095d491ec0afe5cc3f4f7ebd7329ae37855e64dbf83a3d1ac41ff885b
        name: my-java-quarkus
        resources: {}
status: {}
