apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-drawer
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-drawer@sha256:c4e8163b548afc8092bb68671b5c72a4638691c1b75ef9594eebf4eb3baa5c89
        name: my-java-quarkus
        resources: {}
status: {}
