apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-email
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-email
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-email
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-email
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-email
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-email@sha256:dd26c33f639c2d5f95dee08782c0f616ff479908ed886311c3ad3302d6f76550
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9003
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
