apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-aggregator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-aggregator@sha256:8d74550ca36e6e137d1bed36d3b20d61cbb44e7f2db447b7aa8895e50df387b2
        name: my-java-quarkus
        resources: {}
status: {}
