apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: recipients-resolver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: recipients-resolver
    app.kubernetes.io/part-of: notifications-backend
  name: recipients-resolver
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: "9008"
    port: 9008
    targetPort: 9008
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: recipients-resolver
status:
  loadBalancer: {}
