apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-slack
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-slack@sha256:87023dad5a627fbcaf3aceb5773c6bb0f11ed718326904240a08518b29541d4b
        name: my-java-quarkus
        resources: {}
status: {}
