apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-servicenow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-servicenow
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-servicenow
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-servicenow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-servicenow
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-servicenow@sha256:4c00ca2036c839df7f7b77366b8f91acf239e89952d7df7eb6a9d412382777ff
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9003
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
