apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-webhook
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-webhook@sha256:e5bbb4419dd73b5c25cfe06dfe6aa78b114b1ac5ddec0edead01c226c91190a7
        name: my-java-quarkus
        resources: {}
status: {}
