apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: engine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: engine
    app.kubernetes.io/part-of: notifications-backend
  name: enginedqiv
spec:
  path: /
  port:
    targetPort: 9003
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: engine
    weight: null
status: {}
