apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-google-chat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-google-chat
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-google-chat
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-google-chat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-google-chat
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-google-chat@sha256:c3c26bb14643c28851bf99d9c72faea7c3c65369fdd22b0f12b42292918f3628
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9001
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
