apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: notifications-backend
  name: backend
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: backend
status:
  loadBalancer: {}
