apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: engine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: engine
    app.kubernetes.io/part-of: notifications-backend
  name: engine
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: engine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: engine
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/engine@sha256:f96f1082cd6e0417790f9634ac3a7c3e1763f8c6bb92e28e044d3a7ebb3da0b7
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9003
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
