apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-recipients-resolver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-recipients-resolver
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-recipients-resolver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-recipients-resolver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-recipients-resolver
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-recipients-resolver@sha256:170918e571fbfc2d7d3f60b9dca6d95ae386025878031ab7ad2aef8726d1e7b8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9008
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
