apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: connector-slack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: connector-slack
    app.kubernetes.io/part-of: notifications-backend
  name: connector-slack
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: "9004"
    port: 9004
    targetPort: 9004
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: connector-slack
status:
  loadBalancer: {}
