apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-email
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-email@sha256:fad9f7f71d445c1c2d8217c62f8e220e32cbbe6414308812c160bee7d7d5080c
        name: my-java-quarkus
        resources: {}
status: {}
