apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-servicenow
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-servicenow@sha256:cad2eac30648e379890b6ab1d2e1757239b3d058893c84be6beaea15d1b71817
        name: my-java-quarkus
        resources: {}
status: {}
