apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-engine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-engine
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-engine
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-engine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-engine
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-engine@sha256:57061b58ca20a06effdef4265bcd28e59f891c43d7f97ddae00ce125b71e01cb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8087
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
