apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-drawer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-drawer
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-drawer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-drawer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-drawer
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-drawer@sha256:693ae2027bf1e0bf5ca864b73bb0510c45a0b40096a5b4b432a9fe47f1ae4148
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9007
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
