apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-webhook
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-webhook
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-webhook
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-webhook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-webhook
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-webhook@sha256:2228dbe3233fd77d98c58c50863686f5d48513f447a453c29604f964a71bcab1
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9006
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
