apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-microsoft-teams
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-microsoft-teams
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-microsoft-teams
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-microsoft-teams
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-microsoft-teams
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-microsoft-teams@sha256:c698ee4671af5831b71b868442160a4063d4a2b22a21c2d52a88ccb8c37ac5f0
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9002
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
