apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-recipients-resolver
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-recipients-resolver@sha256:170918e571fbfc2d7d3f60b9dca6d95ae386025878031ab7ad2aef8726d1e7b8
        name: my-java-quarkus
        resources: {}
status: {}
