apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-recipients-resolver
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-recipients-resolver@sha256:04ea46c72e88aa3f6c241bfa2968217db91547d2923d6fc57fcf9497b29ddb50
        name: my-java-quarkus
        resources: {}
status: {}
