apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-recipients-resolver
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-recipients-resolver@sha256:fe3eabd57e40c88f2e0e6d2ef9ed335b311c5090fc385d7d26f283d3cc6828e1
        name: my-java-quarkus
        resources: {}
status: {}
