apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-backend
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-backend
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-backend@sha256:32a6f5a65acf19ea3974488b15c32e624a361036b967e3e32fc8ab8b38db3292
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8085
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
