apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-backend
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-backend@sha256:a8e4da6145116dd898066820a60050054913f7908bb4f5618b268924e4b0af51
        name: my-java-quarkus
        resources: {}
status: {}
