apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-connector-google-chat
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-google-chat@sha256:104a190af2fa9494e37457efb1989f5a9d1f0966c8af95d7843e7b0092571a09
        name: my-java-quarkus
        resources: {}
status: {}
