apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-splunk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-splunk
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-splunk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-splunk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-splunk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-splunk@sha256:2957110a0b73d061cb2c80f61e5f3d602ab8f2e4bb07292d0019e110bd3b4b90
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9005
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
