apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-connector-splunk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-connector-splunk
    app.kubernetes.io/part-of: notifications-backend
  name: notifications-connector-splunk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-connector-splunk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-connector-splunk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-connector-splunk@sha256:99ea3613649fd43e81416b7b9e43bb4f1da9bf42896d068035652191cdd0233b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9005
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
