apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-engine
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-engine@sha256:7b7c0451e1250d291b246b0c32ac45814d9cdb57e390bc5c43512700885206b5
        name: my-java-quarkus
        resources: {}
status: {}
