apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-engine
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-engine@sha256:9748ba9df80efc8204e73e1f366c3bdc3299212793931ea9f53c48ecd131a92b
        name: my-java-quarkus
        resources: {}
status: {}
