apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: notifications-engine
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-backend/notifications-engine@sha256:ef775b0b092ba6e5dd52a5881f33a667ad786695cd86bf666ca918312073d7be
        name: my-java-quarkus
        resources: {}
status: {}
